name: Check Types / Lint

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
      - ".vscode/**"
      - "catalog-info.yaml"
      - "**.md"
      - ".gitignore"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cp .env.example .env.local
    - run: npm ci
    - run: npm run check-types
    - run: npm run lint
