name: Check Types / Lint

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
      - ".vscode/**"
      - "catalog-info.yaml"
      - "**.md"
      - ".gitignore"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  release:
    types: [published]

# Cancel this workflow if it is in progress when a new commit is added to the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g npm@${{  needs.get-versions.outputs.npmVersion  }} --legacy-peer-deps
    - run: npm run check-types
    - run: npm run lint
